### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by X-alim** [kphurley/swlcgdb#25]
- Variable  search options (Traits, text, name, damage icons, uniqueness, faction, resource cost, HP, edge icons)
- all cards per set visible when you click on one seperately 
- filter options for each force pack/deluxe

- Total edge/unit/resource amount per card set visible/searchable? (If you want to fill out a deck with a specific type of card)
- Perhaps a warning if you have less than 6 resource cards in deck (which I believe was the advised minimum)

**Comment by kphurley** [comment]
Hey, thanks for the submission!

> all cards per set visible when you click on one separately
I'm addressing this one already somewhat.  Most of the lists are organized by objective.  You click on one in a table and theres a dropdown for the rest.

I think you mean though that if you go to a page for a specific card, you can see a list of all of the cards in its objective set and navigate to those.  That should be pretty easy to implement.

> Variable search options
I have traits, text and name done already, I don't think the others would be too hard.

> Filter options for each force pack/deluxe
I assume you mean while deckbuilding or just viewing?  Definitely something I hope to implement at some point, might not be in first release though.

> Total edge/unit/resource amount per card set visible/searchable?
> a warning if you have less than 6 resource cards
Might need more color on these, can you elaborate?

**Comment by kphurley** [comment]
> all cards per set visible when you click on one seperately
This is done now

> Variable search options (Traits, text, name, damage icons, uniqueness, faction, resource cost, HP, edge icons)
Traits, text, name, faction and cost are in.
